# Generated by Django 3.2.13 on 2022-05-09 18:41

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220509_2044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('blog', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
