# Generated by Django 3.2.13 on 2022-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Heading of post')),
                ('text', models.TextField(verbose_name='text of post')),
            ],
        ),
        migrations.CreateModel(
            name='Rost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique number')),
                ('heading', models.CharField(max_length=100, verbose_name='Heading of post')),
                ('text', models.TextField(verbose_name='text of post')),
            ],
        ),
    ]
