# Generated by Django 3.2.13 on 2022-05-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kost_rost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rost',
            old_name='heading',
            new_name='qheading',
        ),
        migrations.RenameField(
            model_name='rost',
            old_name='text',
            new_name='qtext',
        ),
        migrations.RemoveField(
            model_name='kost',
            name='id',
        ),
        migrations.AddField(
            model_name='kost',
            name='rost_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.rost'),
            preserve_default=False,
        ),
    ]
