# Generated by Django 3.2.13 on 2022-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220509_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='heading',
            field=models.CharField(max_length=100, verbose_name='Heading of post122'),
        ),
        migrations.AlterField(
            model_name='kost',
            name='text',
            field=models.TextField(verbose_name='text of post122'),
        ),
    ]
