# Generated by Django 3.2.13 on 2022-05-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220509_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='Rost',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rost', to='api.rost', verbose_name='Author of blog'),
            preserve_default=False,
        ),
    ]
