# Generated by Django 3.2.13 on 2022-05-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_kost_rost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='new', max_length=100, verbose_name='Name of blog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kost',
        ),
        migrations.DeleteModel(
            name='Rost',
        ),
    ]
