# Generated by Django 3.2.13 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_follow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Subscribe to bloga'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Set flag about reading the post'),
        ),
    ]
