# Generated by Django 3.2.13 on 2022-05-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220510_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_subscribed',
        ),
    ]
