# Generated by Django 3.2.13 on 2022-05-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='date_create',
            new_name='date',
        ),
    ]
